version: "3.8"
services:
  discovery:
    hostname: discovery-server
    container_name: discovery-server
    build:
      context: discoveryserver/
      dockerfile: Dockerfile
    image: discovery-server:latest
    ports:
      - "8761:8761"
    networks:
      - sensor-cloud
  sensorservice:
    hostname: sensor-service
    container_name: sensor-service
    build:
      context: sensorservice/
      dockerfile: Dockerfile
    image: sensor-service:latest
    ports:
      - "8200:8200"
    networks:
      - sensor-cloud

networks:
  sensor-cloud:
